### ISSUE TITLE
Error: No hooks

### ISSUE THREAD

**Issue by gagangiri94** [alphagov/icinga_slack_webhook#5]
in icinga logs i am seeing this error
"Error: No hooks"

i also tried to run the command `icinga_slack_webhook_notify  -c Channel_id -m MESSAGE -s subdomain -t our_slack_token` .  but getting the same error-
Error: No hooks

**Comment by cbaines** [comment]
Hello,

Quite a bit of the code has changed since you raised this issue. Could you perhaps try with version 2.1.1? 

I'm going to close this, but if you're still encountering this problem, please open a new issue (and link to this one).

Thanks,

Chris
